;;; org-canvas-contract-test.el --- Contract tests against Canvas OpenAPI  -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later

;;; Commentary:

;; Validates that each module's build-payload output conforms to the Canvas
;; create-operation request contract extracted from the OpenAPI spec
;; (documentation/architecture/canvas-openapi3.yaml).
;;
;; The contract is a compact JSON fixture generated by
;; test/contract/extract-canvas-contract.py — re-run that script when the
;; OpenAPI spec changes.  Reading JSON keeps this test free of any YAML
;; dependency at run time.
;;
;; For every covered module the test asserts, on the wrapped payload:
;;   * REQUIRED  — every required spec field is present
;;   * UNKNOWN   — every emitted field is a documented spec field (or a
;;                 justified, documented exception)
;;   * ENUM      — every emitted field that the spec constrains to an enum
;;                 carries a legal value
;;
;; This structurally catches the whole "renamed / dropped / mistyped /
;; illegal-enum field" bug class across modules, rather than relying on a
;; handcrafted assertion per field.

;;; Code:

(require 'buttercup)
(require 'test-helper)
(require 'org-canvas)
(require 'json)
(require 'seq)
(require 'cl-lib)

(defconst org-canvas-contract--fixture
  (let ((rel "test/contract/canvas-contract.json"))
    (cond
     ((file-exists-p rel) (expand-file-name rel))
     ((file-exists-p (expand-file-name rel default-directory))
      (expand-file-name rel default-directory))
     (t rel)))
  "Path to the generated Canvas contract JSON fixture.")

(defconst org-canvas-contract--data
  (when (file-exists-p org-canvas-contract--fixture)
    (let ((json-object-type 'alist)
          (json-array-type 'list)
          (json-key-type 'string))
      (json-read-file org-canvas-contract--fixture)))
  "Parsed contract fixture, or nil when the fixture is missing.")

(defconst org-canvas-contract--exceptions
  ;; Fields a module legitimately emits that the documented create operation
  ;; omits.  Each must be justified — these are not free passes.
  '(("modules" . ("published")))
  "Per-module allowed-but-undocumented payload fields.
modules: Canvas honors `module[published]' on create even though the
documented create_module operation does not list it; org-canvas relies on
this to publish modules in a single request.")

;;;; Helpers

(defun org-canvas-contract--inner-keys (payload wrapper)
  "Return the string field names at the WRAPPER level of PAYLOAD.
PAYLOAD may be an alist or a hash-table; WRAPPER is nil for flat payloads."
  (let ((inner payload))
    (when wrapper
      (setq inner (cond ((hash-table-p payload) (gethash wrapper payload))
                        ((listp payload) (alist-get (intern wrapper) payload)))))
    (cond
     ((hash-table-p inner)
      (let (ks) (maphash (lambda (k _v) (push (format "%s" k) ks)) inner) ks))
     ((listp inner)
      (mapcar (lambda (kv) (format "%s" (car kv))) inner))
     (t nil))))

(defun org-canvas-contract--inner-get (payload wrapper key)
  "Return the value of string KEY at the WRAPPER level of PAYLOAD."
  (let ((inner payload))
    (when wrapper
      (setq inner (cond ((hash-table-p payload) (gethash wrapper payload))
                        ((listp payload) (alist-get (intern wrapper) payload)))))
    (cond
     ((hash-table-p inner) (gethash key inner))
     ((listp inner) (alist-get (intern key) inner))
     (t nil))))

(defun org-canvas-contract--build (org parse-fn build-fn)
  "Parse the ORG snippet at its first heading and return the built payload."
  (let ((tmp (make-temp-file "contract-" nil ".org")))
    (unwind-protect
        (progn
          (with-temp-file tmp (insert org))
          (with-current-buffer (find-file-noselect tmp)
            (unwind-protect
                (progn
                  (goto-char (point-min))
                  (re-search-forward "^\\*+ ")
                  (org-back-to-heading)
                  (funcall build-fn (funcall parse-fn)))
              (kill-buffer))))
      (delete-file tmp))))

(defun org-canvas-contract--check (module org parse-fn build-fn)
  "Assert MODULE's build-payload conforms to its Canvas contract.
ORG is a representative heading snippet; PARSE-FN/BUILD-FN are the module's
stage-1/2 functions."
  (let* ((contract (alist-get module org-canvas-contract--data nil nil #'string=))
         (wrapper (alist-get "wrapper" contract nil nil #'string=))
         (fields (alist-get "fields" contract nil nil #'string=))
         (required (alist-get "required" contract nil nil #'string=))
         (allowed (append (mapcar #'car fields)
                          (alist-get module org-canvas-contract--exceptions
                                     nil nil #'string=)))
         (org-canvas-course-id "99999")
         (org-canvas-base-url "https://test.canvas.example.com")
         (org-canvas-api-token "test-token")
         (payload (org-canvas-contract--build org parse-fn build-fn))
         (keys (org-canvas-contract--inner-keys payload wrapper)))
    (expect contract :to-be-truthy)
    ;; REQUIRED: every required spec field present.
    (dolist (req required)
      (expect (member req keys)
              :to-be-truthy))
    ;; UNKNOWN: every emitted field documented (or justified exception).
    (dolist (k keys)
      (expect (member k allowed)
              :to-be-truthy))
    ;; ENUM: emitted string values must be legal where the spec constrains them.
    (dolist (k keys)
      (let* ((fspec (alist-get k fields nil nil #'string=))
             (enum (alist-get "enum" fspec nil nil #'string=))
             (val (org-canvas-contract--inner-get payload wrapper k)))
        (when (and enum (stringp val))
          (expect (member val enum) :to-be-truthy))))))

;;;; Tests

(describe "Canvas request-body contract"
  (it "ships the generated contract fixture"
    ;; If this fails, run: python3 test/contract/extract-canvas-contract.py
    (expect (file-exists-p org-canvas-contract--fixture) :to-be-truthy)
    (expect org-canvas-contract--data :to-be-truthy))

  (it "assignments build-payload conforms to create_assignment"
    (org-canvas-contract--check
     "assignments"
     "* Essay\n:PROPERTIES:\n:POINTS: 50\n:GRADING_TYPE: points\n:SUBMISSION: online_upload\n:PUBLISHED: true\n:END:\n\nWrite an essay.\n"
     #'org-canvas--assignment-parse-entry #'org-canvas--assignment-build-payload))

  (it "quizzes build-payload conforms to create_quiz"
    (org-canvas-contract--check
     "quizzes"
     "* Quiz 1\n:PROPERTIES:\n:QUIZ_TYPE: practice_quiz\n:PUBLISHED: true\n:END:\n\nIntro text.\n"
     #'org-canvas--quiz-parse-entry #'org-canvas--quiz-build-payload))

  (it "modules build-payload conforms to create_module"
    (org-canvas-contract--check
     "modules"
     "* Week 1\n:PROPERTIES:\n:PUBLISHED: true\n:POSITION: 2\n:END:\n"
     #'org-canvas--module-parse-entry #'org-canvas--module-build-payload))

  (it "pages build-payload conforms to create_page"
    (org-canvas-contract--check
     "pages"
     "* Welcome\n:PROPERTIES:\n:PUBLISHED: false\n:END:\n\nHi.\n"
     #'org-canvas--page-parse-entry #'org-canvas--page-build-payload))

  (it "calendar build-payload conforms to create_calendar_event"
    (org-canvas-contract--check
     "calendar"
     "* Office Hours\n:PROPERTIES:\n:START_AT: <2026-09-01 Tue 14:00>\n:END:\n\nDrop by.\n"
     #'org-canvas--calendar-event-parse-entry
     #'org-canvas--calendar-event-build-payload))

  (it "assignment-groups build-payload conforms to create_assignment_group"
    (org-canvas-contract--check
     "assignment-groups"
     "* Homework\n:PROPERTIES:\n:WEIGHT: 30\n:END:\n"
     #'org-canvas--assignment-group-parse-entry
     #'org-canvas--assignment-group-build-payload))

  (it "group-categories build-payload conforms to create_group_category"
    (org-canvas-contract--check
     "group-categories"
     "* Teams\n:PROPERTIES:\n:SELF_SIGNUP: enabled\n:GROUP_LIMIT: 4\n:END:\n"
     #'org-canvas--group-category-parse-entry
     #'org-canvas--group-category-build-payload))

  (it "announcements build-payload conforms to create discussion_topic"
    (org-canvas-contract--check
     "announcements"
     "* Welcome\n:PROPERTIES:\n:PUBLISHED: true\n:END:\n\nHi class.\n"
     #'org-canvas--announcement-parse-entry
     #'org-canvas--announcement-build-payload))

  (it "discussions build-payload conforms to create discussion_topic"
    (org-canvas-contract--check
     "discussions"
     "* Topic\n:PROPERTIES:\n:DISCUSSION_TYPE: threaded\n:END:\n\nDiscuss.\n"
     #'org-canvas--discussion-parse-entry
     #'org-canvas--discussion-build-payload)))

;;;; Pull-side contract
;;
;; The request-body contract above checks what we SEND.  This checks the READ
;; path: a module's pull-item must tolerate the full documented Canvas response
;; object (every field in the component schema) without error, and read the
;; fields it depends on.  Dummy values are typed from the spec so structured
;; fields (arrays/objects) don't trip the pull code.

(defun org-canvas-contract--dummy (type)
  "Return a type-appropriate dummy value for a documented response field TYPE."
  (cond ((member type '("integer" "number")) 1)
        ((equal type "boolean") t)
        ((equal type "string") "x")
        (t nil)))                       ; array / object / unknown

(defun org-canvas-contract--response (module)
  "Build a response alist with every documented response field for MODULE."
  (let* ((entry (alist-get module org-canvas-contract--data nil nil #'string=))
         (fields (alist-get "response_fields" entry nil nil #'string=)))
    (mapcar (lambda (kv)
              (cons (intern (car kv)) (org-canvas-contract--dummy (cdr kv))))
            fields)))

(describe "Canvas response (pull) contract"
  (it "assignment pull-item tolerates the full documented response"
    (let ((response (org-canvas-contract--response "assignments")))
      (expect response :to-be-truthy)
      (with-temp-org-buffer "* A\n:PROPERTIES:\n:CANVAS_ID: 1\n:END:\n"
        (org-back-to-heading)
        ;; Must not error on the full documented shape, and must read the
        ;; documented `points_possible' field into POINTS.
        (org-canvas--assignment-pull-item response (point))
        (expect (org-entry-get (point) "POINTS") :to-be-truthy))))

  (it "assignment-group pull-item tolerates the full documented response"
    (let ((response (org-canvas-contract--response "assignment-groups")))
      (expect response :to-be-truthy)
      (with-temp-org-buffer "* G\n:PROPERTIES:\n:CANVAS_ID: 1\n:END:\n"
        (org-back-to-heading)
        (org-canvas--assignment-group-pull-item response (point))
        (expect (org-entry-get (point) "WEIGHT") :to-be-truthy)))))

(provide 'org-canvas-contract-test)
;;; org-canvas-contract-test.el ends here
