;;; org-canvas-graphql-contract-test.el --- GraphQL documents against the Canvas schema  -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later

;;; Commentary:

;; Checks the GraphQL documents org-canvas sends, and the variables
;; their callers build, against the Canvas GraphQL schema (issue #269) —
;; the GraphQL side of what test/org-canvas-contract-test.el does for the
;; REST payloads.
;;
;; The schema is a compact JSON fixture, test/contract/canvas-graphql-
;; contract.json, generated by test/contract/extract-canvas-graphql-
;; contract.py from the instance's introspection or from the SDL
;; instructure/canvas-lms ships; it holds only the types the documents
;; reach.  Re-run the script when a document changes, when a live GraphQL
;; run fails, or when a Canvas release lands.
;;
;; Each document is named by its symbol and checked as a whole: every
;; selected field exists on its parent type and is not deprecated; every
;; argument exists and a variable's declared type fits it; every non-null
;; field of an input literal is supplied; enum literals are members; a
;; leaf is not selected into and an object is.  There is no GraphQL
;; parser in Elisp, so the documents are tokenized here — they are one
;; line each, of a regular shape.
;;
;; The variables side is the real analogue of the REST build-payload
;; check: the checkpoint input builders and the four other callers run
;; with the sender mocked, and what they hand it is checked against the
;; fixture's input types — key exists, required key present, scalar kind
;; right (a Boolean! from t or :json-false and never nil, an ID! a
;; string, a list a vector so it encodes as a JSON array), enum strings
;; valid.

;;; Code:

(require 'buttercup)
(require 'test-helper)
(require 'org-canvas)
(require 'json)
(require 'cl-lib)

;;;; The fixture

(defconst org-canvas-graphql-contract--fixture
  (let ((rel "test/contract/canvas-graphql-contract.json"))
    (cond
     ((file-exists-p rel) (expand-file-name rel))
     ((file-exists-p (expand-file-name rel default-directory))
      (expand-file-name rel default-directory))
     (t rel)))
  "Path to the generated Canvas GraphQL contract fixture.")

(defconst org-canvas-graphql-contract--data
  (when (file-exists-p org-canvas-graphql-contract--fixture)
    (let ((json-object-type 'hash-table)
          (json-array-type 'list)
          (json-key-type 'string))
      (json-read-file org-canvas-graphql-contract--fixture)))
  "Parsed fixture, or nil when it is missing.")

(defconst org-canvas-graphql-contract--documents
  '(org-canvas--assignment-post-policy-mutation
    org-canvas--settings-post-policy-mutation
    org-canvas--submissions-post-grades-mutation
    org-canvas--discussion-checkpoints-query
    org-canvas--discussion-checkpoints-mutation
    org-canvas--assignment-processors-query
    org-canvas--submissions-reports-query)
  "The documents, by symbol.  A new one is added here and to the
extractor's SOURCES when its file is new.")

(defun org-canvas-graphql-contract--type (name)
  "Return the fixture entry of the named type NAME, or nil."
  (gethash name (gethash "types" org-canvas-graphql-contract--data)))

(defun org-canvas-graphql-contract--named (type-ref)
  "Return the named type inside TYPE-REF, a GraphQL type string.
`[DiscussionCheckpoints!]' gives `DiscussionCheckpoints'."
  (replace-regexp-in-string "[][!]" "" type-ref))

(defun org-canvas-graphql-contract--non-null-p (type-ref)
  "Return non-nil when TYPE-REF is non-null at its top level."
  (string-suffix-p "!" type-ref))

(defun org-canvas-graphql-contract--list-p (type-ref)
  "Return non-nil when TYPE-REF is a list at its top level."
  (string-prefix-p "[" (string-remove-suffix "!" type-ref)))

(defun org-canvas-graphql-contract--element (type-ref)
  "Return the element type of the list TYPE-REF."
  (let ((inner (string-remove-suffix "!" type-ref)))
    (substring inner 1 -1)))

(defun org-canvas-graphql-contract--compatible-p (variable location)
  "Return non-nil when a variable of type VARIABLE may fill LOCATION.
The types must agree, except that a non-null variable may fill a
nullable location."
  (or (equal variable location)
      (equal (string-remove-suffix "!" variable) location)))

;;;; Tokenizer and parser

(defun org-canvas-graphql-contract--tokenize (document)
  "Return DOCUMENT's tokens as (KIND . TEXT) pairs.
KIND is `punct', `name', `var', `string' or `number'; commas are
insignificant and dropped."
  (let ((pos 0) (tokens nil)
        (re (concat "[ \t\n,]*\\(?:"
                    "\\([][{}():!=]\\)"
                    "\\|\\$\\([A-Za-z_][A-Za-z0-9_]*\\)"
                    "\\|\\([A-Za-z_][A-Za-z0-9_]*\\)"
                    "\\|\"\\([^\"]*\\)\""
                    "\\|\\(-?[0-9]+\\(?:\\.[0-9]+\\)?\\)"
                    "\\)")))
    (while (< pos (length document))
      (unless (eq (string-match re document pos) pos)
        (error "Cannot tokenize GraphQL at %d: %S" pos (substring document pos)))
      (cond ((match-beginning 1) (push (cons 'punct (match-string 1 document)) tokens))
            ((match-beginning 2) (push (cons 'var (match-string 2 document)) tokens))
            ((match-beginning 3) (push (cons 'name (match-string 3 document)) tokens))
            ((match-beginning 4) (push (cons 'string (match-string 4 document)) tokens))
            ((match-beginning 5) (push (cons 'number (match-string 5 document)) tokens)))
      (setq pos (match-end 0))
      (when (string-match-p "\\`[ \t\n,]*\\'" (substring document pos))
        (setq pos (length document))))
    (nreverse tokens)))

(defvar org-canvas-graphql-contract--tokens nil
  "The tokens left to parse, consumed front to back.")

(defun org-canvas-graphql-contract--peek ()
  "Return the next token without consuming it."
  (car org-canvas-graphql-contract--tokens))

(defun org-canvas-graphql-contract--next ()
  "Consume and return the next token."
  (pop org-canvas-graphql-contract--tokens))

(defun org-canvas-graphql-contract--expect (kind &optional text)
  "Consume the next token, which must be of KIND (and TEXT when given)."
  (let ((token (org-canvas-graphql-contract--next)))
    (unless (and (eq (car token) kind) (or (null text) (equal (cdr token) text)))
      (error "GraphQL parse: expected %s %s, got %S" kind (or text "") token))
    (cdr token)))

(defun org-canvas-graphql-contract--punct-p (text)
  "Return non-nil when the next token is the punctuator TEXT."
  (let ((token (org-canvas-graphql-contract--peek)))
    (and (eq (car token) 'punct) (equal (cdr token) text))))

(defun org-canvas-graphql-contract--parse-type ()
  "Parse a type reference and return it as a GraphQL type string."
  (let ((text (if (org-canvas-graphql-contract--punct-p "[")
                  (progn (org-canvas-graphql-contract--next)
                         (prog1 (concat "[" (org-canvas-graphql-contract--parse-type) "]")
                           (org-canvas-graphql-contract--expect 'punct "]")))
                (org-canvas-graphql-contract--expect 'name))))
    (if (org-canvas-graphql-contract--punct-p "!")
        (progn (org-canvas-graphql-contract--next) (concat text "!"))
      text)))

(defun org-canvas-graphql-contract--parse-value ()
  "Parse a value: a variable, literal, enum name, object or list."
  (let ((token (org-canvas-graphql-contract--peek)))
    (pcase (car token)
      ('var (org-canvas-graphql-contract--next) (cons 'var (cdr token)))
      ('string (org-canvas-graphql-contract--next) (cons 'string (cdr token)))
      ('number (org-canvas-graphql-contract--next) (cons 'number (cdr token)))
      ('name (org-canvas-graphql-contract--next)
             (if (member (cdr token) '("true" "false"))
                 (cons 'boolean (cdr token))
               (cons 'enum (cdr token))))
      ('punct
       (pcase (cdr token)
         ("{" (org-canvas-graphql-contract--next)
          (let ((fields nil))
            (while (not (org-canvas-graphql-contract--punct-p "}"))
              (let ((key (org-canvas-graphql-contract--expect 'name)))
                (org-canvas-graphql-contract--expect 'punct ":")
                (push (cons key (org-canvas-graphql-contract--parse-value)) fields)))
            (org-canvas-graphql-contract--next)
            (cons 'object (nreverse fields))))
         ("[" (org-canvas-graphql-contract--next)
          (let ((items nil))
            (while (not (org-canvas-graphql-contract--punct-p "]"))
              (push (org-canvas-graphql-contract--parse-value) items))
            (org-canvas-graphql-contract--next)
            (cons 'list (nreverse items))))
         (_ (error "GraphQL parse: unexpected %S" token)))))))

(defun org-canvas-graphql-contract--parse-arguments ()
  "Parse an optional argument list into (NAME . VALUE) pairs."
  (when (org-canvas-graphql-contract--punct-p "(")
    (org-canvas-graphql-contract--next)
    (let ((args nil))
      (while (not (org-canvas-graphql-contract--punct-p ")"))
        (let ((name (org-canvas-graphql-contract--expect 'name)))
          (org-canvas-graphql-contract--expect 'punct ":")
          (push (cons name (org-canvas-graphql-contract--parse-value)) args)))
      (org-canvas-graphql-contract--next)
      (nreverse args))))

(defun org-canvas-graphql-contract--parse-selections ()
  "Parse a selection set into (:name :args :selections) plists."
  (org-canvas-graphql-contract--expect 'punct "{")
  (let ((fields nil))
    (while (not (org-canvas-graphql-contract--punct-p "}"))
      (let* ((name (org-canvas-graphql-contract--expect 'name))
             (args (org-canvas-graphql-contract--parse-arguments))
             (sub (when (org-canvas-graphql-contract--punct-p "{")
                    (org-canvas-graphql-contract--parse-selections))))
        (push (list :name name :args args :selections sub) fields)))
    (org-canvas-graphql-contract--next)
    (nreverse fields)))

(defun org-canvas-graphql-contract--parse (document)
  "Parse DOCUMENT into (:operation :variables :selections).
:variables are (NAME . TYPE-STRING) pairs."
  (let ((org-canvas-graphql-contract--tokens (org-canvas-graphql-contract--tokenize document)))
    (let ((operation (org-canvas-graphql-contract--expect 'name))
          (variables nil))
      (unless (member operation '("query" "mutation"))
        (error "GraphQL parse: not an operation: %s" operation))
      (when (org-canvas-graphql-contract--punct-p "(")
        (org-canvas-graphql-contract--next)
        (while (not (org-canvas-graphql-contract--punct-p ")"))
          (let ((name (org-canvas-graphql-contract--expect 'var)))
            (org-canvas-graphql-contract--expect 'punct ":")
            (push (cons name (org-canvas-graphql-contract--parse-type)) variables)))
        (org-canvas-graphql-contract--next))
      (prog1 (list :operation operation
                   :variables (nreverse variables)
                   :selections (org-canvas-graphql-contract--parse-selections))
        (when org-canvas-graphql-contract--tokens
          (error "GraphQL parse: trailing tokens %S" org-canvas-graphql-contract--tokens))))))

;;;; The document check

(defvar org-canvas-graphql-contract--problems nil
  "The problems a check has found so far, newest first.")

(defun org-canvas-graphql-contract--problem (format &rest args)
  "Record the problem FORMAT with ARGS."
  (push (apply #'format format args) org-canvas-graphql-contract--problems))

(defun org-canvas-graphql-contract--check-required (entry named where supplied-p)
  "Record each non-null field of the input ENTRY, NAMED, that SUPPLIED-P denies.
A field with a default needs no value.  WHERE names the place."
  (maphash (lambda (name field)
             (when (and (org-canvas-graphql-contract--non-null-p (gethash "type" field))
                        (not (eq (gethash "hasDefault" field) t))
                        (not (funcall supplied-p name)))
               (org-canvas-graphql-contract--problem "%s: %s requires %s (%s)" where named name
                                                     (gethash "type" field))))
           (gethash "fields" entry)))

(defun org-canvas-graphql-contract--enum-member-p (entry name)
  "Return non-nil when NAME is a value of the enum ENTRY."
  (memq (gethash name (gethash "values" entry) 'absent) '(nil :null)))

(defun org-canvas-graphql-contract--check-literal-variable (value type-ref where variables)
  "Check the variable reference VALUE against TYPE-REF at WHERE.
VARIABLES are the document's declarations."
  (let ((declared (cdr (assoc (cdr value) variables))))
    (cond ((null declared)
           (org-canvas-graphql-contract--problem "%s: variable $%s is not declared" where (cdr value)))
          ((not (org-canvas-graphql-contract--compatible-p declared type-ref))
           (org-canvas-graphql-contract--problem "%s: variable $%s is %s but the location takes %s"
                                                 where (cdr value) declared type-ref)))))

(defun org-canvas-graphql-contract--check-literal-scalar (value named where)
  "Check the literal VALUE against the scalar NAMED at WHERE."
  (let ((expected (pcase named
                    ("Boolean" '(boolean))
                    ((or "Int" "Float") '(number))
                    ("ID" '(string number))
                    (_ '(string)))))
    (unless (memq (car value) expected)
      (org-canvas-graphql-contract--problem "%s: %s takes %s, not %s" where named expected (car value)))))

(defun org-canvas-graphql-contract--check-literal-enum (value named entry where)
  "Check the literal VALUE against the enum NAMED, its fixture ENTRY, at WHERE."
  (cond ((not (eq (car value) 'enum))
         (org-canvas-graphql-contract--problem "%s: %s takes an enum literal, not %s" where named (car value)))
        ((not (org-canvas-graphql-contract--enum-member-p entry (cdr value)))
         (org-canvas-graphql-contract--problem "%s: %s is not a value of %s" where (cdr value) named))))

(defun org-canvas-graphql-contract--check-literal-input (value named entry where variables)
  "Check the object literal VALUE against the input type NAMED, ENTRY, at WHERE.
VARIABLES are the document's declarations, for a variable inside it."
  (if (not (eq (car value) 'object))
      (org-canvas-graphql-contract--problem "%s: %s takes an object literal, not %s" where named (car value))
    (let ((fields (gethash "fields" entry)))
      (dolist (pair (cdr value))
        (let ((field (gethash (car pair) fields)))
          (cond ((null field)
                 (org-canvas-graphql-contract--problem "%s: %s has no input field %s" where named (car pair)))
                (t
                 (when (gethash "deprecated" field)
                   (org-canvas-graphql-contract--problem "%s: %s.%s is deprecated: %s" where named (car pair)
                                                         (gethash "deprecated" field)))
                 (org-canvas-graphql-contract--check-literal
                  (cdr pair) (gethash "type" field) (format "%s.%s" named (car pair)) variables)))))
      (org-canvas-graphql-contract--check-required
       entry named where (lambda (name) (assoc name (cdr value)))))))

(defun org-canvas-graphql-contract--check-literal (value type-ref where variables)
  "Check the parsed literal VALUE against TYPE-REF at WHERE.
VARIABLES are the document's declarations, for a variable value."
  (let* ((named (org-canvas-graphql-contract--named type-ref))
         (entry (org-canvas-graphql-contract--type named)))
    (cond
     ((eq (car value) 'var)
      (org-canvas-graphql-contract--check-literal-variable value type-ref where variables))
     ((null entry)
      (org-canvas-graphql-contract--problem "%s: type %s is not in the fixture" where named))
     ((org-canvas-graphql-contract--list-p type-ref)
      (if (eq (car value) 'list)
          (dolist (item (cdr value))
            (org-canvas-graphql-contract--check-literal
             item (org-canvas-graphql-contract--element type-ref) where variables))
        (org-canvas-graphql-contract--problem "%s: %s takes a list, not %s" where type-ref (car value))))
     (t
      (pcase (gethash "kind" entry)
        ("ENUM" (org-canvas-graphql-contract--check-literal-enum value named entry where))
        ("SCALAR" (org-canvas-graphql-contract--check-literal-scalar value named where))
        ("INPUT_OBJECT" (org-canvas-graphql-contract--check-literal-input value named entry where variables))
        (kind (org-canvas-graphql-contract--problem "%s: cannot check a %s" where kind)))))))

(defun org-canvas-graphql-contract--check-arguments (selection field where variables)
  "Check SELECTION's arguments against FIELD's, at WHERE, given VARIABLES."
  (let ((args (gethash "args" field)))
    (dolist (arg (plist-get selection :args))
      (let ((type-ref (gethash (car arg) args)))
        (if (null type-ref)
            (org-canvas-graphql-contract--problem "%s has no argument %s" where (car arg))
          (org-canvas-graphql-contract--check-literal
           (cdr arg) type-ref (format "%s(%s)" where (car arg)) variables))))))

(defun org-canvas-graphql-contract--check-selection-type (selection field where variables)
  "Check what SELECTION selects into against FIELD's type, at WHERE.
A leaf takes no selection and an object needs one; VARIABLES are the
document's declarations."
  (let* ((named (org-canvas-graphql-contract--named (gethash "type" field)))
         (target (org-canvas-graphql-contract--type named))
         (kind (and target (gethash "kind" target)))
         (sub (plist-get selection :selections)))
    (cond ((null target)
           (org-canvas-graphql-contract--problem "%s: type %s is not in the fixture" where named))
          ((and sub (not (member kind '("OBJECT" "INTERFACE"))))
           (org-canvas-graphql-contract--problem "%s is a %s and cannot be selected into" where kind))
          ((and (not sub) (member kind '("OBJECT" "INTERFACE" "UNION")))
           (org-canvas-graphql-contract--problem "%s is an %s and needs a selection" where kind))
          (sub (org-canvas-graphql-contract--check-selections sub named variables)))))

(defun org-canvas-graphql-contract--check-selection (selection parent fields variables)
  "Check one SELECTION against the FIELDS of the type PARENT, given VARIABLES."
  (let* ((name (plist-get selection :name))
         (where (format "%s.%s" parent name))
         (field (gethash name fields)))
    (cond ((null field)
           (org-canvas-graphql-contract--problem "%s has no field %s" parent name))
          (t
           (when (gethash "deprecated" field)
             (org-canvas-graphql-contract--problem "%s is deprecated: %s" where (gethash "deprecated" field)))
           (org-canvas-graphql-contract--check-arguments selection field where variables)
           (org-canvas-graphql-contract--check-selection-type selection field where variables)))))

(defun org-canvas-graphql-contract--check-selections (selections parent variables)
  "Check SELECTIONS against the fixture type named PARENT.
VARIABLES are the document's declarations."
  (let ((entry (org-canvas-graphql-contract--type parent)))
    (if (null entry)
        (org-canvas-graphql-contract--problem "type %s is not in the fixture" parent)
      (dolist (selection selections)
        (org-canvas-graphql-contract--check-selection
         selection parent (gethash "fields" entry) variables)))))

(defun org-canvas-graphql-contract--check-document (document)
  "Return the problems of DOCUMENT against the fixture, oldest first.
Nil when it is clean."
  (let ((org-canvas-graphql-contract--problems nil)
        (parsed (org-canvas-graphql-contract--parse document)))
    (dolist (variable (plist-get parsed :variables))
      (let ((named (org-canvas-graphql-contract--named (cdr variable))))
        (unless (org-canvas-graphql-contract--type named)
          (org-canvas-graphql-contract--problem "variable $%s: type %s is not in the fixture"
                                                (car variable) named))))
    (org-canvas-graphql-contract--check-selections
     (plist-get parsed :selections)
     (gethash (plist-get parsed :operation) (gethash "roots" org-canvas-graphql-contract--data))
     (plist-get parsed :variables))
    (nreverse org-canvas-graphql-contract--problems)))

;;;; The variables check

(defun org-canvas-graphql-contract--check-value-list (value type-ref where)
  "Check the Lisp VALUE against the list TYPE-REF at WHERE.
A vector, each item checked."
  (if (vectorp value)
      (let ((i 0))
        (mapc (lambda (item)
                (org-canvas-graphql-contract--check-value
                 item (org-canvas-graphql-contract--element type-ref) (format "%s[%d]" where i))
                (cl-incf i))
              value))
    (org-canvas-graphql-contract--problem "%s: %s must be a vector to encode as a JSON array, not %S"
                                          where type-ref value)))

(defun org-canvas-graphql-contract--check-value-scalar (value named where)
  "Check the Lisp VALUE against the scalar NAMED at WHERE."
  (unless (pcase named
            ("Boolean" (memq value '(t :json-false)))
            ((or "Int" "Float") (numberp value))
            ("ID" (or (stringp value) (numberp value)))
            (_ (stringp value)))
    (org-canvas-graphql-contract--problem "%s: %S does not encode as a %s" where value named)))

(defun org-canvas-graphql-contract--check-value-input (value named entry where)
  "Check the Lisp alist VALUE against the input type NAMED, ENTRY, at WHERE."
  (if (not (and (consp value) (consp (car value))))
      (org-canvas-graphql-contract--problem "%s: %s takes an alist, not %S" where named value)
    (let ((fields (gethash "fields" entry)))
      (dolist (pair value)
        (let* ((key (symbol-name (car pair)))
               (field (gethash key fields)))
          (if (null field)
              (org-canvas-graphql-contract--problem "%s: %s has no input field %s" where named key)
            (org-canvas-graphql-contract--check-value
             (cdr pair) (gethash "type" field) (format "%s.%s" where key)))))
      (org-canvas-graphql-contract--check-required
       entry named where (lambda (name) (assq (intern name) value))))))

(defun org-canvas-graphql-contract--check-value (value type-ref where)
  "Check the Lisp VALUE a caller built against TYPE-REF at WHERE.
Nil stands for JSON null and fits only a nullable type; a list is
a vector, since `json-encode' writes a Lisp list as an object."
  (let* ((named (org-canvas-graphql-contract--named type-ref))
         (entry (org-canvas-graphql-contract--type named)))
    (cond
     ((null entry)
      (org-canvas-graphql-contract--problem "%s: type %s is not in the fixture" where named))
     ((null value)
      (when (org-canvas-graphql-contract--non-null-p type-ref)
        (org-canvas-graphql-contract--problem "%s is nil, which encodes as null, but is %s"
                                              where type-ref)))
     ((org-canvas-graphql-contract--list-p type-ref)
      (org-canvas-graphql-contract--check-value-list value type-ref where))
     (t
      (pcase (gethash "kind" entry)
        ("ENUM" (unless (and (stringp value) (org-canvas-graphql-contract--enum-member-p entry value))
                  (org-canvas-graphql-contract--problem "%s: %S is not a value of %s" where value named)))
        ("SCALAR" (org-canvas-graphql-contract--check-value-scalar value named where))
        ("INPUT_OBJECT" (org-canvas-graphql-contract--check-value-input value named entry where))
        (kind (org-canvas-graphql-contract--problem "%s: cannot check a %s" where kind)))))))

(defun org-canvas-graphql-contract--check-variables (document variables)
  "Return the problems of VARIABLES, an alist a caller built for DOCUMENT.
Every declared variable is checked against its type; a nullable one
may be absent."
  (let ((org-canvas-graphql-contract--problems nil))
    (dolist (declared (plist-get (org-canvas-graphql-contract--parse document) :variables))
      (let ((pair (assq (intern (car declared)) variables)))
        (if (null pair)
            (when (org-canvas-graphql-contract--non-null-p (cdr declared))
              (org-canvas-graphql-contract--problem "$%s (%s) is not supplied" (car declared) (cdr declared)))
          (org-canvas-graphql-contract--check-value (cdr pair) (cdr declared) (concat "$" (car declared))))))
    (dolist (pair variables)
      (unless (assoc (symbol-name (car pair)) (plist-get (org-canvas-graphql-contract--parse document) :variables))
        (org-canvas-graphql-contract--problem "$%s is supplied but not declared" (car pair))))
    (nreverse org-canvas-graphql-contract--problems)))

(defun org-canvas-graphql-contract--check-input (value type-name)
  "Return the problems of the Lisp VALUE against the input type TYPE-NAME."
  (let ((org-canvas-graphql-contract--problems nil))
    (org-canvas-graphql-contract--check-value value type-name type-name)
    (nreverse org-canvas-graphql-contract--problems)))

(defmacro org-canvas-graphql-contract--capturing (&rest body)
  "Run BODY with the GraphQL senders mocked; return what they were sent.
Each call is a (DOCUMENT . VARIABLES) pair, in order.
A mutation answers the dry-run sentinel; a query answers one empty
page of discussions."
  (declare (indent 0))
  `(let ((sent nil))
     (cl-letf (((symbol-function 'org-canvas--graphql-mutate)
                (lambda (_what document &optional variables)
                  (push (cons document variables) sent)
                  org-canvas--dry-run-response))
               ((symbol-function 'org-canvas--graphql-query)
                (lambda (document &optional variables)
                  (push (cons document variables) sent)
                  '((course . ((discussionsConnection
                                . ((pageInfo . ((hasNextPage . :json-false) (endCursor . :null)))
                                   (nodes . [])))))))))
       ,@body)
     (nreverse sent)))

;;;; Specs

(describe "the GraphQL contract fixture"
  (it "is present, from a named source, and covers the files that carry a document"
    (expect org-canvas-graphql-contract--data :not :to-be nil)
    (let ((provenance (gethash "provenance" org-canvas-graphql-contract--data)))
      (expect (gethash "source" provenance) :to-match "\\`\\(sdl\\|introspection\\)\\'")
      (expect (gethash "generated" provenance) :to-match "\\`[0-9]\\{4\\}-[0-9]\\{2\\}-[0-9]\\{2\\}\\'"))
    (expect (gethash "documents" org-canvas-graphql-contract--data)
            :to-equal '("lisp/org-canvas-assignments.el" "lisp/org-canvas-discussions.el"
                        "lisp/org-canvas-settings.el" "lisp/org-canvas-submissions.el"))
    (expect (gethash "query" (gethash "roots" org-canvas-graphql-contract--data)) :to-equal "Query")
    (expect (gethash "mutation" (gethash "roots" org-canvas-graphql-contract--data)) :to-equal "Mutation")))

(describe "the GraphQL documents against the schema"
  (dolist (symbol org-canvas-graphql-contract--documents)
    (it (format "%s validates" symbol)
      (expect (org-canvas-graphql-contract--check-document (symbol-value symbol)) :to-equal nil)))
  (it "parses each document as one operation with its variables"
    (let ((parsed (org-canvas-graphql-contract--parse org-canvas--discussion-checkpoints-mutation)))
      (expect (plist-get parsed :operation) :to-equal "mutation")
      (expect (plist-get parsed :variables)
              :to-equal '(("topicId" . "ID!") ("checkpoints" . "[DiscussionCheckpoints!]")))
      (let ((field (car (plist-get parsed :selections))))
        (expect (plist-get field :name) :to-equal "updateDiscussionTopic")
        (expect (plist-get field :args)
                :to-equal '(("input" . (object ("discussionTopicId" . (var . "topicId"))
                                               ("setCheckpoints" . (boolean . "true"))
                                               ("checkpoints" . (var . "checkpoints"))))))
        (expect (mapcar (lambda (s) (plist-get s :name)) (plist-get field :selections))
                :to-equal '("discussionTopic" "errors"))))
    (let ((parsed (org-canvas-graphql-contract--parse org-canvas--discussion-checkpoints-query)))
      (expect (plist-get parsed :operation) :to-equal "query")
      (expect (plist-get (car (plist-get parsed :selections)) :args)
              :to-equal '(("id" . (var . "courseId"))))))
  (it "refuses what the schema does not have, so a passing document means something"
    (expect (org-canvas-graphql-contract--check-document
             "query ($id: ID!) { course(id: $id) { nope } }")
            :to-equal '("Course has no field nope"))
    (expect (org-canvas-graphql-contract--check-document
             "mutation ($id: ID!) { setCoursePostPolicy(input: {courseId: $id}) { postPolicy { postManually } } }")
            :to-equal '("Mutation.setCoursePostPolicy(input): SetCoursePostPolicyInput requires postManually (Boolean!)"))
    (expect (org-canvas-graphql-contract--check-document
             "mutation ($id: ID!, $manual: String!) { setCoursePostPolicy(input: {courseId: $id, postManually: $manual}) { postPolicy { postManually } } }")
            :to-equal '("SetCoursePostPolicyInput.postManually: variable $manual is String! but the location takes Boolean!"))
    (expect (org-canvas-graphql-contract--check-document
             "mutation ($id: ID!) { updateDiscussionTopic(input: {discussionTopicId: $id, checkpoints: [{checkpointLabel: reply_to_nobody, pointsPossible: 1, dates: []}]}) { discussionTopic { _id } } }")
            :to-equal '("DiscussionCheckpoints.checkpointLabel: reply_to_nobody is not a value of CheckpointLabelType"))
    (expect (org-canvas-graphql-contract--check-document
             "query ($id: ID!) { course(id: $id) { name { x } } }")
            :to-equal '("Course.name is a SCALAR and cannot be selected into"))
    (expect (org-canvas-graphql-contract--check-document
             "query ($id: ID!) { course(id: $id, sisId: 4) { discussionsConnection } }")
            :to-equal '("Query.course(sisId): String takes (string), not number"
                        "Course.discussionsConnection is an OBJECT and needs a selection"))
    (expect (org-canvas-graphql-contract--check-document
             "query ($id: ID!, $n: Nope) { course(id: $id, sisId: $s) { _id } }")
            :to-equal '("variable $n: type Nope is not in the fixture"
                        "Query.course(sisId): variable $s is not declared"))))

(describe "the variables the callers build, against the fixture's input types"
  (it "org-canvas--discussion-checkpoint-input fills DiscussionCheckpoints"
    (expect (org-canvas-graphql-contract--check-input
             (org-canvas--discussion-checkpoint-input "reply_to_topic" 5 "2026-10-01T04:59:59Z")
             "DiscussionCheckpoints")
            :to-equal nil)
    (expect (org-canvas-graphql-contract--check-input
             (org-canvas--discussion-checkpoint-input "reply_to_entry" 2.5 nil 3)
             "DiscussionCheckpoints")
            :to-equal nil))
  (it "org-canvas--discussion-checkpoints-inputs fills the mutation's checkpoints list"
    (let ((inputs (org-canvas--discussion-checkpoints-inputs
                   (list :topic-points 5 :topic-due-at "2026-10-01T04:59:59Z"
                         :reply-points 3 :reply-due-at nil :replies-required 2))))
      (expect (org-canvas-graphql-contract--check-input inputs "[DiscussionCheckpoints!]")
              :to-equal nil)))
  (it "catches an input a builder could get wrong"
    (expect (org-canvas-graphql-contract--check-input
             '((checkpointLabel . "reply_to_topic") (pointsPossible . "5") (dates . []))
             "DiscussionCheckpoints")
            :to-equal '("DiscussionCheckpoints.pointsPossible: \"5\" does not encode as a Float"))
    (expect (org-canvas-graphql-contract--check-input
             '((checkpointLabel . "reply_to_topic") (pointsPossible . 5) (dates . (((type . "everyone")))))
             "DiscussionCheckpoints")
            :to-equal '("DiscussionCheckpoints.dates: [DiscussionCheckpointDate!]! must be a vector to encode as a JSON array, not (((type . \"everyone\")))"))
    (expect (org-canvas-graphql-contract--check-input
             '((checkpointLabel . "reply_to_topic") (pointsPossible . 5) (dates . [((type . "sometimes") (due . "x"))]))
             "DiscussionCheckpoints")
            :to-equal '("DiscussionCheckpoints.dates[0].type: \"sometimes\" is not a value of DiscussionCheckpointDateType"
                        "DiscussionCheckpoints.dates[0]: DiscussionCheckpointDate has no input field due")))
  (it "org-canvas--assignment-push-post-policy sends what its mutation declares"
    (with-org-canvas-test-config
      (let ((sent (org-canvas-graphql-contract--capturing
                    (org-canvas--assignment-push-post-policy
                     (list :title "Essay" :post-policy "manual") 1001)
                    (org-canvas--assignment-push-post-policy
                     (list :title "Essay" :post-policy "auto") "1002"))))
        (expect (length sent) :to-equal 2)
        (dolist (call sent)
          (expect (car call) :to-be org-canvas--assignment-post-policy-mutation)
          (expect (org-canvas-graphql-contract--check-variables (car call) (cdr call)) :to-equal nil)))))
  (it "org-canvas--settings-push-post-policy sends what its mutation declares"
    (with-org-canvas-test-config
      (let ((sent (org-canvas-graphql-contract--capturing
                    (org-canvas--settings-push-post-policy (list :post-policy "auto")))))
        (expect (length sent) :to-equal 1)
        (expect (caar sent) :to-be org-canvas--settings-post-policy-mutation)
        (expect (org-canvas-graphql-contract--check-variables (caar sent) (cdar sent)) :to-equal nil)
        ;; The Boolean! is t or :json-false, never nil: nil would encode as null.
        (expect (alist-get 'manual (cdar sent)) :to-be :json-false))))
  (it "org-canvas-submissions-post-grades sends what its mutation declares"
    (with-org-canvas-test-config
      (with-temp-buffer
        (org-mode)
        (insert "#+PROPERTY: CANVAS_ASSIGNMENT_ID 1001\n")
        (org-canvas-submissions-mode 1)
        (let ((sent (org-canvas-graphql-contract--capturing
                      (org-canvas-submissions-post-grades))))
          (expect (length sent) :to-equal 1)
          (expect (caar sent) :to-be org-canvas--submissions-post-grades-mutation)
          (expect (org-canvas-graphql-contract--check-variables (caar sent) (cdar sent)) :to-equal nil)))))
  (it "org-canvas--discussion-checkpoints-fetch sends what its query declares, with and without a cursor"
    (with-org-canvas-test-config
      (let ((sent (org-canvas-graphql-contract--capturing
                    (org-canvas--discussion-checkpoints-fetch))))
        (expect (length sent) :to-equal 1)
        (expect (caar sent) :to-be org-canvas--discussion-checkpoints-query)
        (expect (org-canvas-graphql-contract--check-variables (caar sent) (cdar sent)) :to-equal nil))
      ;; The second page carries the cursor the first one answered with.
      (let ((pages 0) (sent nil))
        (cl-letf (((symbol-function 'org-canvas--graphql-query)
                   (lambda (document &optional variables)
                     (push (cons document variables) sent)
                     (cl-incf pages)
                     `((course . ((discussionsConnection
                                   . ((pageInfo . ((hasNextPage . ,(if (= pages 1) t :json-false))
                                                   (endCursor . ,(if (= pages 1) "Mg" :null))))
                                      (nodes . [])))))))))
          (org-canvas--discussion-checkpoints-fetch))
        (expect (length sent) :to-equal 2)
        (dolist (call sent)
          (expect (org-canvas-graphql-contract--check-variables (car call) (cdr call)) :to-equal nil))
        (expect (alist-get 'cursor (cdar sent)) :to-equal "Mg"))))
  (it "org-canvas--assignment-processors-fetch sends what its query declares, with and without a cursor"
    (with-org-canvas-test-config
      (let ((pages 0) (sent nil))
        (cl-letf (((symbol-function 'org-canvas--graphql-query)
                   (lambda (document &optional variables)
                     (push (cons document variables) sent)
                     (cl-incf pages)
                     `((course . ((assignmentsConnection
                                   . ((pageInfo . ((hasNextPage . ,(if (= pages 1) t :json-false))
                                                   (endCursor . ,(if (= pages 1) "Mg" :null))))
                                      (nodes . [])))))))))
          (org-canvas--assignment-processors-fetch))
        (expect (length sent) :to-equal 2)
        (dolist (call sent)
          (expect (car call) :to-be org-canvas--assignment-processors-query)
          (expect (org-canvas-graphql-contract--check-variables (car call) (cdr call)) :to-equal nil))
        (expect (assq 'cursor (cdr (car (last sent)))) :to-be nil)
        (expect (alist-get 'cursor (cdar sent)) :to-equal "Mg"))))
  (it "org-canvas--submissions-fetch-reports sends what its query declares, with and without a cursor"
    (with-org-canvas-test-config
      (let ((pages 0) (sent nil))
        (cl-letf (((symbol-function 'org-canvas--graphql-query)
                   (lambda (document &optional variables)
                     (push (cons document variables) sent)
                     (cl-incf pages)
                     `((assignment
                        . ((submissionsConnection
                            . ((pageInfo . ((hasNextPage . ,(if (= pages 1) t :json-false))
                                            (endCursor . ,(if (= pages 1) "Mg" :null))))
                               (nodes . [])))))))))
          (org-canvas--submissions-fetch-reports 1001))
        (expect (length sent) :to-equal 2)
        (dolist (call sent)
          (expect (car call) :to-be org-canvas--submissions-reports-query)
          (expect (org-canvas-graphql-contract--check-variables (car call) (cdr call)) :to-equal nil))
        (expect (alist-get 'assignmentId (cdar sent)) :to-equal "1001")
        (expect (alist-get 'cursor (cdar sent)) :to-equal "Mg"))))
  (it "org-canvas--discussion-push-checkpoints sends what its mutation declares"
    (with-org-canvas-test-config
      (let ((sent (org-canvas-graphql-contract--capturing
                    (org-canvas--discussion-push-checkpoints
                     (list :title "Week 3"
                           :checkpoints (list :topic-points 5 :topic-due-at "2026-10-01T04:59:59Z"
                                              :reply-points 3 :reply-due-at "2026-10-03T04:59:59Z"
                                              :replies-required 2))
                     4242))))
        (expect (length sent) :to-equal 1)
        (expect (caar sent) :to-be org-canvas--discussion-checkpoints-mutation)
        (expect (org-canvas-graphql-contract--check-variables (caar sent) (cdar sent)) :to-equal nil)
        (expect (org-canvas-graphql-contract--check-variables
                 (caar sent) '((topicId . nil) (checkpoints . nil) (extra . 1)))
                :to-equal '("$topicId is nil, which encodes as null, but is ID!"
                            "$extra is supplied but not declared"))))))

(provide 'org-canvas-graphql-contract-test)
;;; org-canvas-graphql-contract-test.el ends here
