;;; org-canvas-doc-reference-test.el --- Manual property-reference drift guard  -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later

;;; Commentary:

;; Guards the single source of truth for property documentation: the
;; "Property Reference" appendix of documentation/manual.org is generated
;; from the property registry by test/docgen/generate-property-reference.el.
;;
;; This test regenerates that section from the live registry and asserts the
;; committed manual still matches.  If it fails, the registry changed without
;; regenerating the docs — run:
;;
;;   eldev emacs --batch -l test/docgen/generate-property-reference.el \
;;     --eval '(org-canvas-docgen-write "documentation/manual.org")'
;;
;; Comparison normalizes whitespace so Org table re-alignment never causes a
;; false failure; structural content (rows, cells) is what must match.

;;; Code:

(require 'buttercup)
(require 'test-helper)
(require 'org-canvas)

(defconst org-canvas-doc-ref--generator
  (let ((rel "test/docgen/generate-property-reference.el"))
    (cond ((file-exists-p rel) (expand-file-name rel))
          ((file-exists-p (expand-file-name rel default-directory))
           (expand-file-name rel default-directory))
          (t rel)))
  "Path to the property-reference generator.")

(defconst org-canvas-doc-ref--manual
  (let ((rel "documentation/manual.org"))
    (cond ((file-exists-p rel) (expand-file-name rel))
          ((file-exists-p (expand-file-name rel default-directory))
           (expand-file-name rel default-directory))
          (t rel)))
  "Path to the user manual.")

(when (file-exists-p org-canvas-doc-ref--generator)
  (load org-canvas-doc-ref--generator nil t))

(defun org-canvas-doc-ref--normalize (text)
  "Normalize TEXT for whitespace-insensitive comparison.
Trims each line, collapses internal whitespace runs, drops blank lines."
  (let (out)
    (dolist (line (split-string (or text "") "\n"))
      (let ((norm (string-trim
                   (replace-regexp-in-string "[ \t]+" " " line)))
            )
        (unless (string-empty-p norm)
          (push norm out))))
    (nreverse out)))

(defun org-canvas-doc-ref--region (file)
  "Return the text between the AUTOGENERATED markers in FILE, or nil."
  (with-temp-buffer
    (insert-file-contents file)
    (goto-char (point-min))
    (when (search-forward org-canvas-docgen-begin-marker nil t)
      (let ((beg (line-end-position)))
        (when (search-forward org-canvas-docgen-end-marker nil t)
          (buffer-substring-no-properties
           beg (line-beginning-position)))))))

(describe "manual Property Reference (SSOT drift guard)"
  (it "loads the generator"
    (expect (fboundp 'org-canvas-docgen-body) :to-be-truthy))

  (it "is present in the committed manual"
    (expect (file-exists-p org-canvas-doc-ref--manual) :to-be-truthy)
    (expect (org-canvas-doc-ref--region org-canvas-doc-ref--manual)
            :to-be-truthy))

  (it "matches what the registry generates (regenerate if this fails)"
    (let ((committed (org-canvas-doc-ref--normalize
                      (org-canvas-doc-ref--region org-canvas-doc-ref--manual)))
          (generated (org-canvas-doc-ref--normalize
                      (org-canvas-docgen-body))))
      (expect committed :to-equal generated))))

(provide 'org-canvas-doc-reference-test)
;;; org-canvas-doc-reference-test.el ends here
