;;; generate-property-reference.el --- Generate manual property reference -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later

;;; Commentary:

;; Dev tooling (not shipped in the package).  Generates the "Property
;; Reference" appendix of documentation/manual.org from the property
;; registry, making the registry the single source of truth for property
;; names, types, allowed values, defaults, and descriptions.
;;
;; The generated region is delimited by AUTOGENERATED markers; everything
;; outside them (the hand-written manual) is left untouched.
;;
;; Regenerate after changing any `org-canvas-register-properties' call:
;;
;;     eldev emacs --batch -l test/docgen/generate-property-reference.el \
;;       --eval '(org-canvas-docgen-write "documentation/manual.org")'
;;
;; A drift guard (test/org-canvas-doc-reference-test.el) fails if the
;; committed manual no longer matches what the registry would generate.

;;; Code:

(require 'org-canvas)
(require 'cl-lib)
(require 'subr-x)

(defconst org-canvas-docgen-begin-marker
  "# BEGIN AUTOGENERATED PROPERTY REFERENCE"
  "Marker line opening the generated region in the manual.")

(defconst org-canvas-docgen-end-marker
  "# END AUTOGENERATED PROPERTY REFERENCE"
  "Marker line closing the generated region in the manual.")

(defun org-canvas-docgen--cell (s)
  "Sanitize S for use inside an Org table cell."
  (let ((s (or s "")))
    ;; Org tables use | as the column separator; escape any literal bars.
    (replace-regexp-in-string "|" "\\\\vert{}" (string-trim s))))

(defun org-canvas-docgen--allowed (prop)
  "Return the \"allowed values\" cell text for property spec PROP."
  (let ((type (plist-get prop :type))
        (values (plist-get prop :values)))
    (cond
     (values (mapconcat #'identity values ", "))
     ((eq type 'boolean) "true, false")
     ((eq type 'link) "org link")
     (t ""))))

(defun org-canvas-docgen--default (prop)
  "Return the default-value cell text for property spec PROP."
  (if (plist-member prop :default)
      (if (plist-get prop :default) "true" "false")
    ""))

(defun org-canvas-docgen--feature-table (plist)
  "Return the Org table rows (a string) for registry PLIST, or nil if empty."
  (let ((props (plist-get plist :properties)))
    (when props
      (concat
       "| Property | Type | Allowed values | Default | Description |\n"
       "|----------+------+----------------+---------+-------------|\n"
       (mapconcat
        (lambda (prop)
          (format "| =%s= | %s | %s | %s | %s |"
                  (plist-get prop :org-prop)
                  (symbol-name (or (plist-get prop :type) 'string))
                  (org-canvas-docgen--cell (org-canvas-docgen--allowed prop))
                  (org-canvas-docgen--default prop)
                  (org-canvas-docgen--cell (plist-get prop :doc))))
        props "\n")
       "\n"))))

(defun org-canvas-docgen--features-sorted ()
  "Return registry (feature-name . plist) pairs sorted by label for stability."
  (let (pairs)
    (maphash (lambda (name plist) (push (cons name plist) pairs))
             org-canvas--property-registry)
    (sort pairs (lambda (a b)
                  (string< (or (plist-get (cdr a) :label) (car a))
                           (or (plist-get (cdr b) :label) (car b)))))))

(defun org-canvas-docgen-body ()
  "Return the generated body (between markers) as a string."
  (concat
   "# Generated from the org-canvas property registry by\n"
   "# test/docgen/generate-property-reference.el — do not edit by hand.\n\n"
   (mapconcat
    (lambda (pair)
      (let ((table (org-canvas-docgen--feature-table (cdr pair))))
        (when table
          (format "** %s\n\n%s" (or (plist-get (cdr pair) :label) (car pair))
                  table))))
    (seq-filter (lambda (pair)
                  (org-canvas-docgen--feature-table (cdr pair)))
                (org-canvas-docgen--features-sorted))
    "\n")))

(defun org-canvas-docgen-section ()
  "Return the full Property Reference section, markers included."
  (concat "* Property Reference\n"
          ":PROPERTIES:\n:CUSTOM_ID: property-reference\n:END:\n\n"
          org-canvas-docgen-begin-marker "\n\n"
          (org-canvas-docgen-body) "\n"
          org-canvas-docgen-end-marker "\n"))

(defun org-canvas-docgen-write (file)
  "Write or refresh the Property Reference section in FILE.
Replaces the region between the AUTOGENERATED markers, or appends a new
section if the markers are absent."
  (with-temp-buffer
    (insert-file-contents file)
    (goto-char (point-min))
    (if (search-forward org-canvas-docgen-begin-marker nil t)
        (let ((beg (line-beginning-position)))
          (search-forward org-canvas-docgen-end-marker)
          (delete-region beg (line-end-position))
          (goto-char beg)
          (insert org-canvas-docgen-begin-marker "\n\n"
                  (org-canvas-docgen-body) "\n"
                  org-canvas-docgen-end-marker))
      (goto-char (point-max))
      (unless (bolp) (insert "\n"))
      (insert "\n" (org-canvas-docgen-section)))
    (write-region (point-min) (point-max) file))
  (message "Wrote Property Reference to %s" file))

(provide 'generate-property-reference)
;;; generate-property-reference.el ends here
